### ISSUE TITLE
Some issue to review

### ISSUE THREAD

**Issue by b-t-k** [dazitzel/e-e-smith_the-skylark-of-space#1]
**Just a note**— it's generally better to do a pass to clean up crud like page numbers early in the process so that it doesn't get mixed in with later commits.

### content.opf
- Typo in short description "start"
  - "refines" is a bit extraneous— you could probably just say he "creates a way"

- First line of long desc. is awkward. Change tense to "have consistently influenced"
  - 2nd sentence… delete "which makes"— his quitting is what makes DeQuense willing to do anything. 
  - A "new planet" (singular) vs "civilizations" (plural). Is this correct?
  - I would move the bit in the colophon about this being different than the later publication here as well as a note that *Skylark* was originally published as a 3-part serial. 

 - Change file-as and add full-name metadata for E.E. Smith (see [https://github.com/standardebooks/e-e-smith_triplanetary/blob/master/src/epub/content.opf](https://github.com/standardebooks/e-e-smith_triplanetary/blob/master/src/epub/content.opf)

### preface 
- run modernize-spelling "far-away"
- Title “The Skylark of Space,” should be in `<i>` with appropriate semantics — two instances

### Chapter 3
- Missing se semantication on `<i>Star</i>`

### Chapter 4
- Missing se semantication on `<i>Washington Clarion</i>` - 4 instances
- Missing "strong" on first lines of blockquote. Can target it with css
- Why did you change the "hm-m⁠ ⁠…" to "hmm"? And having done so it should be marked [editorial] *See also Chap 18*

### Chapter 10
- OK is not an abbreviation (see 8.10.9.1)

### Chapter 11
- A Dickybird" … I would revert to "Dicky-bird" as it is a purposeful pun.

### Chapter 13 
- missing space "themselves.Nalboon"
- Should be "salt⁠- and pepper⁠-shakers" with hyphens

### Chapter 17
- Missing semantication on `<i>Kondal</i>`

- the Letter 
  - Eliminate `<div>`
  - Witness section: should it be in a in separate blockquote vs footer? I will ask Alex about this.
  - regardless the signatures need to be in `<span>` not `<strong>`

### Chapter 18
- “Hmm⁠ ⁠… he must have made himself a parachute. 
  - Why did you change the Hm to Hmm? And having done so it should be marked [editorial]

### colophon
- add personal-name semantic on producer since it is not a href
- add abbr on L.N.

### t0c
**Just a note** Make separate commits—you mixed in colophon and imprint changes and it just makes it harder to review.

**Comment by dazitzel** [comment]
All handled by a series of four commits, though see note at end regarding Hm->Hmm.

The largest number of fixes an found in https://github.com/dazitzel/e-e-smith_the-skylark-of-space/commit/57ce2d0557164c6db28a0bbbb5e40e20f312b5c6.
This also introduced some needs to re-typogrify, lint, and clean.

You appear to question that Seaton quitting is which makes DeQuense willing to do anything. I have to say yes it is. DeQuense states quite clearly that Seaton quitting is what caused him to realize that it was real and should be pursued, but I adjusted the short description anyway.

se typogrify and se clean applied with change https://github.com/dazitzel/e-e-smith_the-skylark-of-space/commit/c6927911871880517161fdfbbbddf0ec5c795b72

Not being careful enough in moving a information from the preface to the colophon also required a change to get se lint to run clean again https://github.com/dazitzel/e-e-smith_the-skylark-of-space/commit/7804d4d80934675f2e00d9ec8139c746f8e7deb0

Regarding the marriage certificate in chapter 17.
I finally sat down and made a decision about what the xhmtl should look like.
Then added to local.css to get both that and the newspaper article in chapter 4 to style correctly. I chose z3998:secondary is really the correct semantics but the name appears to fit. Tarnan is the signer and the witnesses are secondary signers. But secondary can mean so many things and the style guide is silent. If I've abused it any suggestions are welcome. https://github.com/dazitzel/e-e-smith_the-skylark-of-space/commit/a77532b1a7f3b42f4621c54549b5b9fa551fa4c9

Final note.
You asked about why I changed Hm to Hmm.
That change was part of modernizing spelling.
Hmm is the most correct and modern spelling for that particular piece of onomatopoeia.
See https://www.merriam-webster.com/dictionary/hmm, which the style guide says is the authority on correct American spellings.

**Comment by b-t-k** [comment]
**Cover** — I didn't notice this last round but we should crop the cover to remove the border and signature.

**content.opf** — Typo in short description: "start"

I still question the use of the word "refines" but I appreciate you not wanting to change the description overly, I can promise you description rarely survive Alex's discerning opinions intact, so let's leave it to him :-)

**Preface** — you need to remove the quote marks around Skylark of Space x 2
—run modernize-spelling to fix "far-away"

**Note** in the follow two issues the actual semantics is secondary to the css styling.

**Chapter 4** header 
The scans have the first 3 lines emphasized. We could adjust the css to  target that (see my suggestion on Chapter 17  as a guide).  

"Harper’s Ferry" should be targeted to have small caps.

**Chapter 17** the semantics of z3998:secondary is "secondary" to just styling it in css. But I believe that putting a blockquote in a blockquote is not quite right here. Alex's suggestion was: "You can put them in a `<ul>` that is styled to remove list formatting."

I think that might work better and you could target it with something like:
```
#chapter-17 footer p:nth-child(2) {
	text-align: left;
}

#chapter-17 footer li {
	list-style-type: none;
	text-align: left;
}
```
Again I am not an expert with css but this is closer to what Standard usually does. We might ask the list for help on both of these if necessary.

**Hmm** Given that it's onomatopoetic I would argue that changing it loses character and flavour but what you chose is fine :-)

**Comment by dazitzel** [comment]
Cover re-cropped.
Start systems actually changed to star systems, and faraway corrected this time.
Heading information and place stylinng updating for chapter 4.
Chapter 17 no longer has a <blockquote> within a <blockquote> but an unadorned <ul> within an unadorned <ul>

**Comment by b-t-k** [comment]
I am going to go ahead and approve it  but I maintain doubts about the single use of a class over the use of the targeted css I suggested

**Comment by dazitzel** [comment]
A pair of nested unordered lists seemed truer to the intant than individually styled line items since it's the entire list that is unadorned.
